### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by RayFerr000** [passcod/mtwitter#8]
I get a 'TypeError: undefined is not a function' when I try to create an mtwitter object. Here is my code:

```
var Twitter = require('mtwitter');
var consumer_key = '###################'
var consumer_secret = '#######################'
var twitter = new Twitter({
  consumer_key: consumer_key,
  consumer_secret: consumer_secret,
  application_only: true
});
```
This is the error:
```/Users/ray/Desktop/What-s_trending/trending/node_modules/mtwitter/node_modules/request/index.js:64
    return this(params.uri || null, params.options, params.callback)
               ^
TypeError: undefined is not a function
    at request.(anonymous function) (/Users/ray/Desktop/What-s_trending/trending/node_modules/mtwitter/node_modules/request/index.js:64:16)
    at TwitterRest.processRequest (/Users/ray/Desktop/What-s_trending/trending/node_modules/mtwitter/lib/rest.js:219:7)
    at TwitterRest.queueRequest (/Users/ray/Desktop/What-s_trending/trending/node_modules/mtwitter/lib/rest.js:125:7)
    at TwitterRest.getAppOnlyToken (/Users/ray/Desktop/What-s_trending/trending/node_modules/mtwitter/lib/rest.js:294:5)
    at new TwitterRest (/Users/ray/Desktop/What-s_trending/trending/node_modules/mtwitter/lib/rest.js:341:5)
    at new Twitter (/Users/ray/Desktop/What-s_trending/trending/node_modules/mtwitter/lib/mtwitter.js:19:14)
    at Object.<anonymous> (/Users/ray/Desktop/What-s_trending/trending/routes/index.js:9:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
```

**Comment by passcod** [comment]
You probably shouldn't use mtwitter. There's better twitter libraries for Node.js and they are actually maintained. Nevertheless, I'll take a look at that this weekend.

**Comment by RayFerr000** [comment]
Thanks for the reply, I will look into other wrappers

**Comment by SeanEire** [comment]
I'm noticing this issue too after deploying to Azure. The same code works fine on my local machine with the same version of the package, might be a conflict with another installed package but I haven't had a chance to investigate further. I see the package is no longer maintained but thought I'd add the comment since I saw the issue open.

**Comment by passcod** [comment]
Is your local machine on Windows too? If yes, are you using straight Windows CLI or going through Cygwin? That might might be a Windows only issue, mmmm.

**Comment by passcod** [comment]
Resolution is to use request 2.53.0 or just not use this library. Closing as mtwitter is slowly getting less usable and I have no interest in fixing it at this moment.

Use [twitter](https://www.npmjs.com/package/twitter) or [twit](https://www.npmjs.com/package/twit) instead.
